Traceback (most recent call last):
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba-root/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%bash
curl --output tmp.zip -L -X GET "https://datadryad.org/api/v2/datasets/doi%3A10.5061%2Fdryad.z612jm6c0/download" -H "accept: application/zip"
unzip tmp.zip
unzip cleaned_up_restless_final_data.zip
rm tmp.zip
rm README.txt
rm cleaned_up_restless_final_data.zip
chmod -R u+wx cleaned\ up\ restless\ final\ data
mv cleaned\ up\ restless\ final\ data data
------------------

----- stderr -----
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
----- stderr -----
                                 Dload  Upload   Total   Spent    Left  Speed
----- stderr -----
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  1477  100  1477    0     0   2655      0 --:--:-- --:--:-- --:--:--  2661
----- stdout -----
Archive:  tmp.zip
----- stderr -----
  End-of-central-directory signature not found.  Either this file is not
----- stderr -----
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
----- stderr -----
  latter case the central directory and zipfile comment will be found on
----- stderr -----
  the last disk(s) of this archive.
----- stderr -----
unzip:  cannot find zipfile directory in one of tmp.zip or
----- stderr -----
        tmp.zip.zip, and cannot find tmp.zip.ZIP, period.
----- stderr -----
unzip:  cannot find or open cleaned_up_restless_final_data.zip, cleaned_up_restless_final_data.zip.zip or cleaned_up_restless_final_data.zip.ZIP.
----- stderr -----
rm: cannot remove 'README.txt': No such file or directory
----- stderr -----
rm: cannot remove 'cleaned_up_restless_final_data.zip': No such file or directory
----- stderr -----
chmod: cannot access 'cleaned up restless final data': No such file or directory
----- stderr -----
mv: cannot stat 'cleaned up restless final data': No such file or directory
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mCalledProcessError[0m                        Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_cell_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mbash[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mcurl --output tmp.zip -L -X GET [39;49m[38;5;124;43m"[39;49m[38;5;124;43mhttps://datadryad.org/api/v2/datasets/doi[39;49m[38;5;124;43m%[39;49m[38;5;124;43m3A10.5061[39;49m[38;5;132;43;01m%2F[39;49;00m[38;5;124;43mdryad.z612jm6c0/download[39;49m[38;5;124;43m"[39;49m[38;5;124;43m -H [39;49m[38;5;124;43m"[39;49m[38;5;124;43maccept: application/zip[39;49m[38;5;124;43m"[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43munzip tmp.zip[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43munzip cleaned_up_restless_final_data.zip[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mrm tmp.zip[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mrm README.txt[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mrm cleaned_up_restless_final_data.zip[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mchmod -R u+wx cleaned[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m up[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m restless[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m final[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m data[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mmv cleaned[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m up[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m restless[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m final[39;49m[38;5;130;43;01m\\[39;49;00m[38;5;124;43m data data[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/micromamba-root/envs/book/lib/python3.12/site-packages/IPython/core/interactiveshell.py:2517[0m, in [0;36mInteractiveShell.run_cell_magic[0;34m(self, magic_name, line, cell)[0m
[1;32m   2515[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[1;32m   2516[0m     args [38;5;241m=[39m (magic_arg_s, cell)
[0;32m-> 2517[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2519[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2520[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2521[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2522[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m~/micromamba-root/envs/book/lib/python3.12/site-packages/IPython/core/magics/script.py:154[0m, in [0;36mScriptMagics._make_script_magic.<locals>.named_script_magic[0;34m(line, cell)[0m
[1;32m    152[0m [38;5;28;01melse[39;00m:
[1;32m    153[0m     line [38;5;241m=[39m script
[0;32m--> 154[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshebang[49m[43m([49m[43mline[49m[43m,[49m[43m [49m[43mcell[49m[43m)[49m

File [0;32m~/micromamba-root/envs/book/lib/python3.12/site-packages/IPython/core/magics/script.py:314[0m, in [0;36mScriptMagics.shebang[0;34m(self, line, cell)[0m
[1;32m    309[0m [38;5;28;01mif[39;00m args[38;5;241m.[39mraise_error [38;5;129;01mand[39;00m p[38;5;241m.[39mreturncode [38;5;241m!=[39m [38;5;241m0[39m:
[1;32m    310[0m     [38;5;66;03m# If we get here and p.returncode is still None, we must have[39;00m
[1;32m    311[0m     [38;5;66;03m# killed it but not yet seen its return code. We don't wait for it,[39;00m
[1;32m    312[0m     [38;5;66;03m# in case it's stuck in uninterruptible sleep. -9 = SIGKILL[39;00m
[1;32m    313[0m     rc [38;5;241m=[39m p[38;5;241m.[39mreturncode [38;5;129;01mor[39;00m [38;5;241m-[39m[38;5;241m9[39m
[0;32m--> 314[0m     [38;5;28;01mraise[39;00m CalledProcessError(rc, cell)

[0;31mCalledProcessError[0m: Command 'b'curl --output tmp.zip -L -X GET "https://datadryad.org/api/v2/datasets/doi%3A10.5061%2Fdryad.z612jm6c0/download" -H "accept: application/zip"\nunzip tmp.zip\nunzip cleaned_up_restless_final_data.zip\nrm tmp.zip\nrm README.txt\nrm cleaned_up_restless_final_data.zip\nchmod -R u+wx cleaned\\ up\\ restless\\ final\\ data\nmv cleaned\\ up\\ restless\\ final\\ data data\n'' returned non-zero exit status 1.

